// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package repository

import (
	"context"
	"time"
)

const createSeeker = `-- name: CreateSeeker :one
INSERT INTO seekers (email)
VALUES ($1)
RETURNING id, email, created_at
`

// Registers a new seeker in the system
func (q *Queries) CreateSeeker(ctx context.Context, email string) (Seeker, error) {
	row := q.db.QueryRowContext(ctx, createSeeker, email)
	var i Seeker
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const getSeekerByEmail = `-- name: GetSeekerByEmail :one
SELECT id, email, created_at
FROM seekers
WHERE email = $1
LIMIT 1
`

// Retrieves a seeker by their unique email address
func (q *Queries) GetSeekerByEmail(ctx context.Context, email string) (Seeker, error) {
	row := q.db.QueryRowContext(ctx, getSeekerByEmail, email)
	var i Seeker
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const upsertOTP = `-- name: UpsertOTP :one
INSERT INTO otp_codes (email, code, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, code, expires_at, used, created_at
`

type UpsertOTPParams struct {
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Inserts or updates an OTP code for a specific email
func (q *Queries) UpsertOTP(ctx context.Context, arg UpsertOTPParams) (OtpCode, error) {
	row := q.db.QueryRowContext(ctx, upsertOTP, arg.Email, arg.Code, arg.ExpiresAt)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const verifyOTP = `-- name: VerifyOTP :one
SELECT id, email, code, expires_at, used, created_at
FROM otp_codes
WHERE email = $1
    AND code = $2
    AND used = false
    AND expires_at > NOW()
LIMIT 1
`

type VerifyOTPParams struct {
	Email string `json:"email"`
	Code  string `json:"code"`
}

// Validates an OTP code and checks for expiration
func (q *Queries) VerifyOTP(ctx context.Context, arg VerifyOTPParams) (OtpCode, error) {
	row := q.db.QueryRowContext(ctx, verifyOTP, arg.Email, arg.Code)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}
