// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

type Occurrence struct {
	ID             uuid.UUID      `json:"id"`
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   interface{}    `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Slug           string         `json:"slug"`
	CreatedAt      time.Time      `json:"created_at"`
}

type OtpCode struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Code      string       `json:"code"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
	CreatedAt time.Time    `json:"created_at"`
}

type Photographer struct {
	ID                      uuid.UUID       `json:"id"`
	Name                    string          `json:"name"`
	Email                   string          `json:"email"`
	Bio                     sql.NullString  `json:"bio"`
	StripeAccountID         sql.NullString  `json:"stripe_account_id"`
	CreatedAt               time.Time       `json:"created_at"`
	UpdatedAt               time.Time       `json:"updated_at"`
	IsFounderCreator        bool            `json:"is_founder_creator"`
	IsFounderAlpha          bool            `json:"is_founder_alpha"`
	FounderDeadline         sql.NullTime    `json:"founder_deadline"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
	CommissionRate          decimal.Decimal `json:"commission_rate"`
}

type Seeker struct {
	ID                  uuid.UUID    `json:"id"`
	Email               string       `json:"email"`
	CreatedAt           time.Time    `json:"created_at"`
	WelcomeDiscountUsed bool         `json:"welcome_discount_used"`
	LastFacialScanAt    sql.NullTime `json:"last_facial_scan_at"`
}
