// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Occurrence struct {
	ID             uuid.UUID      `json:"id"`
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   string         `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Slug           string         `json:"slug"`
	CreatedAt      time.Time      `json:"created_at"`
}

type OtpCode struct {
	ID        int32        `json:"id"`
	Email     string       `json:"email"`
	Code      string       `json:"code"`
	ExpiresAt time.Time    `json:"expires_at"`
	Used      sql.NullBool `json:"used"`
	CreatedAt time.Time    `json:"created_at"`
}

type Photographer struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Email           string         `json:"email"`
	Bio             sql.NullString `json:"bio"`
	StripeAccountID sql.NullString `json:"stripe_account_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type Seeker struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}
