// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photographers.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const getPhotographerTier = `-- name: GetPhotographerTier :one
SELECT id, is_founder_creator, is_founder_alpha, founder_deadline,
    total_revenue_accumulated, commission_rate
FROM photographers
WHERE id = $1
LIMIT 1
`

type GetPhotographerTierRow struct {
	ID                      uuid.UUID       `json:"id"`
	IsFounderCreator        bool            `json:"is_founder_creator"`
	IsFounderAlpha          bool            `json:"is_founder_alpha"`
	FounderDeadline         sql.NullTime    `json:"founder_deadline"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
	CommissionRate          decimal.Decimal `json:"commission_rate"`
}

// Fetches tier status and effective commission rate for payout calculation
func (q *Queries) GetPhotographerTier(ctx context.Context, id uuid.UUID) (GetPhotographerTierRow, error) {
	row := q.db.QueryRowContext(ctx, getPhotographerTier, id)
	var i GetPhotographerTierRow
	err := row.Scan(
		&i.ID,
		&i.IsFounderCreator,
		&i.IsFounderAlpha,
		&i.FounderDeadline,
		&i.TotalRevenueAccumulated,
		&i.CommissionRate,
	)
	return i, err
}

const listPhotographers = `-- name: ListPhotographers :many
SELECT id, name, email, bio, stripe_account_id, created_at, updated_at,
    is_founder_creator, is_founder_alpha, founder_deadline, total_revenue_accumulated, commission_rate
FROM photographers
ORDER BY created_at DESC
`

func (q *Queries) ListPhotographers(ctx context.Context) ([]Photographer, error) {
	rows, err := q.db.QueryContext(ctx, listPhotographers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Photographer
	for rows.Next() {
		var i Photographer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Bio,
			&i.StripeAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsFounderCreator,
			&i.IsFounderAlpha,
			&i.FounderDeadline,
			&i.TotalRevenueAccumulated,
			&i.CommissionRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhotographerRevenue = `-- name: UpdatePhotographerRevenue :one
UPDATE photographers
SET total_revenue_accumulated = total_revenue_accumulated + $2,
    updated_at                = NOW()
WHERE id = $1
RETURNING id, is_founder_creator, is_founder_alpha, total_revenue_accumulated, commission_rate
`

type UpdatePhotographerRevenueParams struct {
	ID                      uuid.UUID       `json:"id"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
}

type UpdatePhotographerRevenueRow struct {
	ID                      uuid.UUID       `json:"id"`
	IsFounderCreator        bool            `json:"is_founder_creator"`
	IsFounderAlpha          bool            `json:"is_founder_alpha"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
	CommissionRate          decimal.Decimal `json:"commission_rate"`
}

// Accumulates revenue after each sale and returns the updated tier row
func (q *Queries) UpdatePhotographerRevenue(ctx context.Context, arg UpdatePhotographerRevenueParams) (UpdatePhotographerRevenueRow, error) {
	row := q.db.QueryRowContext(ctx, updatePhotographerRevenue, arg.ID, arg.TotalRevenueAccumulated)
	var i UpdatePhotographerRevenueRow
	err := row.Scan(
		&i.ID,
		&i.IsFounderCreator,
		&i.IsFounderAlpha,
		&i.TotalRevenueAccumulated,
		&i.CommissionRate,
	)
	return i, err
}
