// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photographers.sql

package repository

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	decimal "github.com/shopspring/decimal"
)

const getPhotographerTier = `-- name: GetPhotographerTier :one
SELECT id, is_founder, is_pioneer, founder_deadline,
    total_revenue_accumulated, commission_rate
FROM photographers
WHERE id = $1
LIMIT 1
`

type GetPhotographerTierRow struct {
	ID                      uuid.UUID       `json:"id"`
	IsFounder               bool            `json:"is_founder"`
	IsPioneer               bool            `json:"is_pioneer"`
	FounderDeadline         sql.NullTime    `json:"founder_deadline"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
	CommissionRate          decimal.Decimal `json:"commission_rate"`
}

// Fetches tier status and effective commission rate for payout calculation
func (q *Queries) GetPhotographerTier(ctx context.Context, id uuid.UUID) (GetPhotographerTierRow, error) {
	row := q.db.QueryRowContext(ctx, getPhotographerTier, id)
	var i GetPhotographerTierRow
	err := row.Scan(
		&i.ID,
		&i.IsFounder,
		&i.IsPioneer,
		&i.FounderDeadline,
		&i.TotalRevenueAccumulated,
		&i.CommissionRate,
	)
	return i, err
}

const updatePhotographerRevenue = `-- name: UpdatePhotographerRevenue :one
UPDATE photographers
SET total_revenue_accumulated = total_revenue_accumulated + $2,
    updated_at                = NOW()
WHERE id = $1
RETURNING id, is_founder, is_pioneer, total_revenue_accumulated, commission_rate
`

type UpdatePhotographerRevenueParams struct {
	ID                      uuid.UUID       `json:"id"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
}

type UpdatePhotographerRevenueRow struct {
	ID                      uuid.UUID       `json:"id"`
	IsFounder               bool            `json:"is_founder"`
	IsPioneer               bool            `json:"is_pioneer"`
	TotalRevenueAccumulated decimal.Decimal `json:"total_revenue_accumulated"`
	CommissionRate          decimal.Decimal `json:"commission_rate"`
}

// Accumulates revenue after each sale and returns the updated tier row
func (q *Queries) UpdatePhotographerRevenue(ctx context.Context, arg UpdatePhotographerRevenueParams) (UpdatePhotographerRevenueRow, error) {
	row := q.db.QueryRowContext(ctx, updatePhotographerRevenue, arg.ID, arg.TotalRevenueAccumulated)
	var i UpdatePhotographerRevenueRow
	err := row.Scan(
		&i.ID,
		&i.IsFounder,
		&i.IsPioneer,
		&i.TotalRevenueAccumulated,
		&i.CommissionRate,
	)
	return i, err
}
