// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package repository

import (
	"context"
)

type Querier interface {
	CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (Occurrence, error)
	GetOccurrenceBySlug(ctx context.Context, slug string) (Occurrence, error)
}

var _ Querier = (*Queries)(nil)
