// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Occurrence struct {
	ID             uuid.UUID      `json:"id"`
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   interface{}    `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Slug           string         `json:"slug"`
	CreatedAt      time.Time      `json:"created_at"`
}

type Photographer struct {
	ID              uuid.UUID      `json:"id"`
	Name            string         `json:"name"`
	Email           string         `json:"email"`
	Bio             sql.NullString `json:"bio"`
	StripeAccountID sql.NullString `json:"stripe_account_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
