// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: occurrences.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO occurrences (
    photographer_id, title, description, location_name, location_geom, start_time, end_time, slug
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, photographer_id, title, description, location_name, location_geom, start_time, end_time, slug, created_at
`

type CreateOccurrenceParams struct {
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   interface{}    `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Slug           string         `json:"slug"`
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, createOccurrence,
		arg.PhotographerID,
		arg.Title,
		arg.Description,
		arg.LocationName,
		arg.LocationGeom,
		arg.StartTime,
		arg.EndTime,
		arg.Slug,
	)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationGeom,
		&i.StartTime,
		&i.EndTime,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getOccurrenceBySlug = `-- name: GetOccurrenceBySlug :one
SELECT id, photographer_id, title, description, location_name, location_geom, start_time, end_time, slug, created_at FROM occurrences
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetOccurrenceBySlug(ctx context.Context, slug string) (Occurrence, error) {
	row := q.db.QueryRowContext(ctx, getOccurrenceBySlug, slug)
	var i Occurrence
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationGeom,
		&i.StartTime,
		&i.EndTime,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}
