// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: occurrences.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOccurrence = `-- name: CreateOccurrence :one
INSERT INTO occurrences (
        photographer_id,
        title,
        description,
        location_name,
        location_geom,
        start_time,
        end_time,
        status,
        slug
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        ST_GeomFromText($5::text, 4326),
        -- Explicit cast to text for SQLC mapping
        $6,
        $7,
        $8,
        $9
    )
RETURNING id,
    photographer_id,
    title,
    description,
    location_name,
    ST_AsText(location_geom)::text AS location_geom,
    -- Casting to text ensures string output
    start_time,
    end_time,
    status,
    slug,
    created_at
`

type CreateOccurrenceParams struct {
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	Column5        string         `json:"column_5"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Slug           string         `json:"slug"`
}

type CreateOccurrenceRow struct {
	ID             uuid.UUID      `json:"id"`
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   string         `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Slug           string         `json:"slug"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) CreateOccurrence(ctx context.Context, arg CreateOccurrenceParams) (CreateOccurrenceRow, error) {
	row := q.db.QueryRowContext(ctx, createOccurrence,
		arg.PhotographerID,
		arg.Title,
		arg.Description,
		arg.LocationName,
		arg.Column5,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.Slug,
	)
	var i CreateOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationGeom,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const createPhotographer = `-- name: CreatePhotographer :one
INSERT INTO photographers (name, email, bio, stripe_account_id)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, bio, stripe_account_id, created_at, updated_at
`

type CreatePhotographerParams struct {
	Name            string         `json:"name"`
	Email           string         `json:"email"`
	Bio             sql.NullString `json:"bio"`
	StripeAccountID sql.NullString `json:"stripe_account_id"`
}

func (q *Queries) CreatePhotographer(ctx context.Context, arg CreatePhotographerParams) (Photographer, error) {
	row := q.db.QueryRowContext(ctx, createPhotographer,
		arg.Name,
		arg.Email,
		arg.Bio,
		arg.StripeAccountID,
	)
	var i Photographer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Bio,
		&i.StripeAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOccurrenceBySlug = `-- name: GetOccurrenceBySlug :one
SELECT id,
    photographer_id,
    title,
    description,
    location_name,
    ST_AsText(location_geom)::text AS location_geom,
    start_time,
    end_time,
    status,
    slug,
    created_at
FROM occurrences
WHERE slug = $1
LIMIT 1
`

type GetOccurrenceBySlugRow struct {
	ID             uuid.UUID      `json:"id"`
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   string         `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Slug           string         `json:"slug"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) GetOccurrenceBySlug(ctx context.Context, slug string) (GetOccurrenceBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getOccurrenceBySlug, slug)
	var i GetOccurrenceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.PhotographerID,
		&i.Title,
		&i.Description,
		&i.LocationName,
		&i.LocationGeom,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const listOccurrencesByPhotographer = `-- name: ListOccurrencesByPhotographer :many
SELECT id,
    photographer_id,
    title,
    description,
    location_name,
    ST_AsText(location_geom)::text AS location_geom,
    start_time,
    end_time,
    status,
    slug,
    created_at
FROM occurrences
WHERE photographer_id = $1
ORDER BY start_time DESC
`

type ListOccurrencesByPhotographerRow struct {
	ID             uuid.UUID      `json:"id"`
	PhotographerID uuid.UUID      `json:"photographer_id"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	LocationName   string         `json:"location_name"`
	LocationGeom   string         `json:"location_geom"`
	StartTime      time.Time      `json:"start_time"`
	EndTime        time.Time      `json:"end_time"`
	Status         string         `json:"status"`
	Slug           string         `json:"slug"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (q *Queries) ListOccurrencesByPhotographer(ctx context.Context, photographerID uuid.UUID) ([]ListOccurrencesByPhotographerRow, error) {
	rows, err := q.db.QueryContext(ctx, listOccurrencesByPhotographer, photographerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOccurrencesByPhotographerRow
	for rows.Next() {
		var i ListOccurrencesByPhotographerRow
		if err := rows.Scan(
			&i.ID,
			&i.PhotographerID,
			&i.Title,
			&i.Description,
			&i.LocationName,
			&i.LocationGeom,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
